baseURL: https://nitpum.com/
languageCode: en-us
title: nitpum
theme: nitpum-blog
enableRobotsTXT: true

params:
  description: nitpum blog
  copyright: Copyright
  author:
    name: nitpum
  logo:
    Permalink: /logo-96x96.jpg
  defaultTheme: auto
  assets:
    safari_pinned_tab: apple-touch-icon.png
  default_cover: blog-cover.jpg
  thirdparty:
    facebook:
      appId: 1724084221209665
  share:
    facebook: true
    twitter: true
  analytics:
    goatCounter:
      url: https://nitpum.goatcounter.com/count
  social:
    facebook: nitpum
    twitter: nitpum
    gitlab: nitpum
    github: nitpum
    kofi: nitpum
    webring: nitpum.com

pagination:
  pagerSize: 18
permalinks:
  post: /post/:contentbasename/

related:
  includeNewer: true
  indices:
    - name: tags
      weight: 90
    - name: keywords
      weight: 100
    - name: date
      weight: 60
  threshold: 60
  toLower: true

markup:
  highlight:
    lineNumbersInTable: true

menu:
  main:
    - name: Posts
      url: /post/
      weight: 1
    - name: Tags
      url: /tags
      weight: 3
